### ISSUE TITLE
Request failed: An update to Mazda app is required to continue

### ISSUE THREAD

**Issue by ctml91** [C64Axel/mz2mqtt#1]
Hello - receiving the below error when trying to run this as a container.

```
2024-09-23 15:04:48 INFO     MQTT connected OK
2024-09-23 15:04:48 INFO     Get all vehicles
2024-09-23 15:04:48 INFO     Retrieving encryption keys
2024-09-23 15:04:49 INFO     Successfully retrieved encryption keys
2024-09-23 15:04:49 INFO     No access token present. Logging in.
2024-09-23 15:04:49 INFO     Logging in as <email>
2024-09-23 15:04:49 INFO     Retrieving public key to encrypt password
2024-09-23 15:04:50 INFO     Sending login request
2024-09-23 15:04:51 INFO     Successfully logged in as <email>
Traceback (most recent call last):
  File "/usr/src/app/./mz2mqtt.py", line 81, in main
    vehicles = await mazda_client.get_vehicles()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/mzlib/client.py", line 27, in get_vehicles
    vec_base_infos_response = await self.controller.get_vec_base_infos()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/mzlib/controller.py", line 21, in get_vec_base_infos
    return await self.connection.api_request("POST", "remoteServices/getVecBaseInfos/v4", body_dict={"internaluserid": "__INTERNAL_ID__"}, needs_keys=True, needs_auth=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/mzlib/connection.py", line 163, in api_request
    return await self.__api_request_retry(method, uri, query_dict, body_dict, needs_keys, needs_auth, num_retries=0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/mzlib/connection.py", line 178, in __api_request_retry
    return await self.__send_api_request(method, uri, query_dict, body_dict, needs_keys, needs_auth)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/mzlib/connection.py", line 252, in __send_api_request
    raise MazdaException("Request failed: " + response_json["error"])
mzlib.exceptions.MazdaException: Request failed: An update to Mazda app is required to continue

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/./mz2mqtt.py", line 140, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/src/app/./mz2mqtt.py", line 83, in main
    raise Exception("Failed to get list of vehicles")
Exception: Failed to get list of vehicles
2024-09-23 15:04:52 ERROR    Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fcba9633d50>
2024-09-23 15:04:52 ERROR    Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fcba980bcb0>, 34884.526640519)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7fcba980b770>, 34886.009325884)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fcba9633e10>
```

```
mqtt:
  host: <server-ip>
  port: 1883             # your mqtt port - default 1883
  user:                  # your mqtt user or empty when no authentication
  password:              # your mqtt password
  topic: mz2mqtt         # your mqtt topic - default mz2mqtt. Leave it default for evcc
  clientname: mz2mqtt    # your mqtt clientname - default mz2mqtt
mazda:
  user: <email>
  password: <password>
  region: MNAO            # your Region (MNAO:North America, MME:Europe, MJO:Japan) - default MME
status:
  wait: 30               # wait time in minutes getting status - default 30
  refreshwait: 2
```

**Comment by C64Axel** [comment]
Hi.
Please excuse that I only saw the issue now.
The data query is based on a library that I did not write. So i am not familiar with the code.
Can you please try it with the region Europe (MME)?

**Comment by C64Axel** [comment]
I change the APP-Version inside the Code. So please try again.

**Comment by C64Axel** [comment]
THIS PROJECT IS NOT MAINTAINED ANY MORE
BECAUSE OF CHANGES IN THE MAZDA API
